# Generated by Django 3.1.1 on 2020-10-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LipaNaMpesaOnline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_request_ID', models.CharField(blank=True, max_length=255, null=True)),
                ('merchant_request_ID', models.CharField(blank=True, max_length=255, null=True)),
                ('result_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt_number', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_date', models.DateTimeField()),
                ('phone_number', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Lipa Na Mpesa Online',
            },
        ),
    ]
